site_name: MLゼミノート
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - search.suggest
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - tables
nav:
  - はじめに: index.md
  - 学習トラック:
    - 1_Numpy入門:
      - tracks/10_numpy.md
      - tracks/10_numpy_array.md
      - tracks/10_numpy_array.md
      - tracks/10_numpy_basic.md
    - 2_pandas入門:
      - tracks/20_pandas.md
      - tracks/20_series_basic.md
      - tracks/20_pandas_basic.md
      - tracks/20_index01.md
      - tracks/20_alter_index.md
      - tracks/20_drop.md
    - 3_scikit-learn基礎: tracks/30_sklearn.md
    - 4_モデル評価: tracks/40_eval.md 